# Automatically generated by: ros2nix --flake --distro jazzy
{ lib, buildRosPackage, ament-cmake, ament-cmake-gtest, controller-manager, diff-drive-controller, hardware-interface, joint-state-broadcaster, libserial-dev, pluginlib, rclcpp, rclcpp-lifecycle, robot-state-publisher, ros2-controllers-test-nodes, ros2controlcli, rviz2 }:
buildRosPackage rec {
  pname = "ros-jazzy-diffdrive-arduino";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-cmake-gtest ];
  propagatedBuildInputs = [ controller-manager diff-drive-controller hardware-interface joint-state-broadcaster libserial-dev pluginlib rclcpp rclcpp-lifecycle robot-state-publisher ros2-controllers-test-nodes ros2controlcli rviz2 ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Demo package of `ros2_control` hardware for DiffBot.";
    license = with lib.licenses; [ asl20 ];
  };
}
